# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c2d_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1630, 962)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/Rinnetensei/.designer/Resourses/artificial_intelligence_64px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 440, 1111, 251))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.gridLayoutWidget_9)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 91, 201))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.optAdam_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optAdam_ChB.setObjectName("optAdam_ChB")
        self.gridLayout_8.addWidget(self.optAdam_ChB, 5, 0, 1, 1)
        self.optSGD_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optSGD_ChB.setChecked(True)
        self.optSGD_ChB.setObjectName("optSGD_ChB")
        self.gridLayout_8.addWidget(self.optSGD_ChB, 0, 0, 1, 1)
        self.optAdadelta_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optAdadelta_ChB.setObjectName("optAdadelta_ChB")
        self.gridLayout_8.addWidget(self.optAdadelta_ChB, 4, 0, 1, 1)
        self.optAdagrad_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optAdagrad_ChB.setObjectName("optAdagrad_ChB")
        self.gridLayout_8.addWidget(self.optAdagrad_ChB, 3, 0, 1, 1)
        self.optAdamax_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optAdamax_ChB.setObjectName("optAdamax_ChB")
        self.gridLayout_8.addWidget(self.optAdamax_ChB, 6, 0, 1, 1)
        self.optRMSprop_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optRMSprop_ChB.setObjectName("optRMSprop_ChB")
        self.gridLayout_8.addWidget(self.optRMSprop_ChB, 1, 0, 1, 1)
        self.optNadam_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.optNadam_ChB.setObjectName("optNadam_ChB")
        self.gridLayout_8.addWidget(self.optNadam_ChB, 7, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget_9)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 241, 201))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cSoftMax_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cSoftMax_ChB.setText("")
        self.cSoftMax_ChB.setObjectName("cSoftMax_ChB")
        self.horizontalLayout_13.addWidget(self.cSoftMax_ChB)
        self.dSoftMax_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dSoftMax_ChB.setChecked(True)
        self.dSoftMax_ChB.setObjectName("dSoftMax_ChB")
        self.horizontalLayout_13.addWidget(self.dSoftMax_ChB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cSELU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cSELU_ChB.setText("")
        self.cSELU_ChB.setChecked(True)
        self.cSELU_ChB.setObjectName("cSELU_ChB")
        self.horizontalLayout_7.addWidget(self.cSELU_ChB)
        self.dSELU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dSELU_ChB.setObjectName("dSELU_ChB")
        self.horizontalLayout_7.addWidget(self.dSELU_ChB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cReLU_ChB.setText("")
        self.cReLU_ChB.setChecked(True)
        self.cReLU_ChB.setObjectName("cReLU_ChB")
        self.horizontalLayout_5.addWidget(self.cReLU_ChB)
        self.dReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dReLU_ChB.setObjectName("dReLU_ChB")
        self.horizontalLayout_5.addWidget(self.dReLU_ChB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cSigmoid_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cSigmoid_ChB.setText("")
        self.cSigmoid_ChB.setObjectName("cSigmoid_ChB")
        self.horizontalLayout_16.addWidget(self.cSigmoid_ChB)
        self.dSigmoid_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dSigmoid_ChB.setChecked(True)
        self.dSigmoid_ChB.setObjectName("dSigmoid_ChB")
        self.horizontalLayout_16.addWidget(self.dSigmoid_ChB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 4, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cTReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cTReLU_ChB.setText("")
        self.cTReLU_ChB.setObjectName("cTReLU_ChB")
        self.horizontalLayout_11.addWidget(self.cTReLU_ChB)
        self.dTReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dTReLU_ChB.setObjectName("dTReLU_ChB")
        self.horizontalLayout_11.addWidget(self.dTReLU_ChB)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cELU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cELU_ChB.setText("")
        self.cELU_ChB.setChecked(True)
        self.cELU_ChB.setObjectName("cELU_ChB")
        self.horizontalLayout_6.addWidget(self.cELU_ChB)
        self.dELU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dELU_ChB.setObjectName("dELU_ChB")
        self.horizontalLayout_6.addWidget(self.dELU_ChB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cSoftSign_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cSoftSign_ChB.setText("")
        self.cSoftSign_ChB.setObjectName("cSoftSign_ChB")
        self.horizontalLayout_15.addWidget(self.cSoftSign_ChB)
        self.dSoftSign_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dSoftSign_ChB.setObjectName("dSoftSign_ChB")
        self.horizontalLayout_15.addWidget(self.dSoftSign_ChB)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 2, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cTanh_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cTanh_ChB.setText("")
        self.cTanh_ChB.setObjectName("cTanh_ChB")
        self.horizontalLayout_14.addWidget(self.cTanh_ChB)
        self.dTanh_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dTanh_ChB.setObjectName("dTanh_ChB")
        self.horizontalLayout_14.addWidget(self.dTanh_ChB)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 3, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cLReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cLReLU_ChB.setText("")
        self.cLReLU_ChB.setObjectName("cLReLU_ChB")
        self.horizontalLayout_9.addWidget(self.cLReLU_ChB)
        self.dLReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dLReLU_ChB.setObjectName("dLReLU_ChB")
        self.horizontalLayout_9.addWidget(self.dLReLU_ChB)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cSoftPlus_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cSoftPlus_ChB.setText("")
        self.cSoftPlus_ChB.setObjectName("cSoftPlus_ChB")
        self.horizontalLayout_12.addWidget(self.cSoftPlus_ChB)
        self.dSoftPlus_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dSoftPlus_ChB.setChecked(True)
        self.dSoftPlus_ChB.setObjectName("dSoftPlus_ChB")
        self.horizontalLayout_12.addWidget(self.dSoftPlus_ChB)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cPReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.cPReLU_ChB.setText("")
        self.cPReLU_ChB.setObjectName("cPReLU_ChB")
        self.horizontalLayout_8.addWidget(self.cPReLU_ChB)
        self.dPReLU_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.dPReLU_ChB.setObjectName("dPReLU_ChB")
        self.horizontalLayout_8.addWidget(self.dPReLU_ChB)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 1, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.gridLayoutWidget_9)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_7)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 281, 201))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lf_MSE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_MSE_ChB.setObjectName("lf_MSE_ChB")
        self.gridLayout_7.addWidget(self.lf_MSE_ChB, 0, 1, 1, 1)
        self.lf_MAPE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_MAPE_ChB.setObjectName("lf_MAPE_ChB")
        self.gridLayout_7.addWidget(self.lf_MAPE_ChB, 2, 1, 1, 1)
        self.lf_sqHingle_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_sqHingle_ChB.setObjectName("lf_sqHingle_ChB")
        self.gridLayout_7.addWidget(self.lf_sqHingle_ChB, 5, 2, 1, 1)
        self.lf_Poisson_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_Poisson_ChB.setObjectName("lf_Poisson_ChB")
        self.gridLayout_7.addWidget(self.lf_Poisson_ChB, 5, 1, 1, 1)
        self.lf_Logcosh = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_Logcosh.setObjectName("lf_Logcosh")
        self.gridLayout_7.addWidget(self.lf_Logcosh, 0, 2, 1, 1)
        self.lf_CCE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_CCE_ChB.setObjectName("lf_CCE_ChB")
        self.gridLayout_7.addWidget(self.lf_CCE_ChB, 1, 2, 1, 1)
        self.lf_sCCE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_sCCE_ChB.setObjectName("lf_sCCE_ChB")
        self.gridLayout_7.addWidget(self.lf_sCCE_ChB, 2, 2, 1, 1)
        self.lf_Hingle_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_Hingle_ChB.setObjectName("lf_Hingle_ChB")
        self.gridLayout_7.addWidget(self.lf_Hingle_ChB, 6, 1, 1, 1)
        self.lf_cHingle_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_cHingle_ChB.setObjectName("lf_cHingle_ChB")
        self.gridLayout_7.addWidget(self.lf_cHingle_ChB, 6, 2, 1, 1)
        self.lf_KDL_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_KDL_ChB.setObjectName("lf_KDL_ChB")
        self.gridLayout_7.addWidget(self.lf_KDL_ChB, 4, 1, 1, 1)
        self.lf_BCE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_BCE_ChB.setObjectName("lf_BCE_ChB")
        self.gridLayout_7.addWidget(self.lf_BCE_ChB, 3, 2, 1, 1)
        self.lf_MAE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_MAE_ChB.setObjectName("lf_MAE_ChB")
        self.gridLayout_7.addWidget(self.lf_MAE_ChB, 1, 1, 1, 1)
        self.lf_MSLE_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_MSLE_ChB.setObjectName("lf_MSLE_ChB")
        self.gridLayout_7.addWidget(self.lf_MSLE_ChB, 3, 1, 1, 1)
        self.lf_CosProx_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        self.lf_CosProx_ChB.setObjectName("lf_CosProx_ChB")
        self.gridLayout_7.addWidget(self.lf_CosProx_ChB, 4, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_7, 1, 2, 1, 1)
        self.learning_params_GB2 = QtWidgets.QGroupBox(self.gridLayoutWidget_9)
        self.learning_params_GB2.setTitle("")
        self.learning_params_GB2.setObjectName("learning_params_GB2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.learning_params_GB2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 411, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.batchSize_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.batchSize_SB.setMinimum(1)
        self.batchSize_SB.setMaximum(100000)
        self.batchSize_SB.setProperty("value", 16)
        self.batchSize_SB.setObjectName("batchSize_SB")
        self.horizontalLayout.addWidget(self.batchSize_SB)
        spacerItem12 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.networkEpoch_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.networkEpoch_SB.setMinimum(2)
        self.networkEpoch_SB.setMaximum(100000)
        self.networkEpoch_SB.setObjectName("networkEpoch_SB")
        self.horizontalLayout.addWidget(self.networkEpoch_SB)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.DatasetPath_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.DatasetPath_LE.setObjectName("DatasetPath_LE")
        self.gridLayout.addWidget(self.DatasetPath_LE, 0, 1, 1, 1)
        self.ModelPath_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.ModelPath_LE.setObjectName("ModelPath_LE")
        self.gridLayout.addWidget(self.ModelPath_LE, 1, 1, 1, 1)
        self.Labels_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.Labels_LE.setObjectName("Labels_LE")
        self.gridLayout.addWidget(self.Labels_LE, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.PlotsPath_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.PlotsPath_LE.setObjectName("PlotsPath_LE")
        self.gridLayout.addWidget(self.PlotsPath_LE, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.DatasetPath_TB = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.DatasetPath_TB.setObjectName("DatasetPath_TB")
        self.gridLayout.addWidget(self.DatasetPath_TB, 0, 2, 1, 1)
        self.ModelsPath_TB = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.ModelsPath_TB.setObjectName("ModelsPath_TB")
        self.gridLayout.addWidget(self.ModelsPath_TB, 1, 2, 1, 1)
        self.LabelPath_TB = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.LabelPath_TB.setObjectName("LabelPath_TB")
        self.gridLayout.addWidget(self.LabelPath_TB, 2, 2, 1, 1)
        self.PlotPath_TB = QtWidgets.QToolButton(self.verticalLayoutWidget_4)
        self.PlotPath_TB.setObjectName("PlotPath_TB")
        self.gridLayout.addWidget(self.PlotPath_TB, 3, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 5)
        self.gridLayout_9.addWidget(self.learning_params_GB2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 431)
        self.gridLayout_9.setColumnStretch(1, 111)
        self.gridLayout_9.setColumnStretch(2, 301)
        self.gridLayout_9.setColumnStretch(3, 261)
        self.gridLayout_9.setRowStretch(0, 1)
        self.gridLayout_9.setRowStretch(1, 10)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 1111, 411))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.evolEpoch_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.evolEpoch_SB.setMinimum(1)
        self.evolEpoch_SB.setMaximum(10000)
        self.evolEpoch_SB.setProperty("value", 10)
        self.evolEpoch_SB.setObjectName("evolEpoch_SB")
        self.horizontalLayout_23.addWidget(self.evolEpoch_SB)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.netName_LE = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.netName_LE.setObjectName("netName_LE")
        self.gridLayout_4.addWidget(self.netName_LE, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem17)
        self.popSize_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.popSize_SB.setMinimum(3)
        self.popSize_SB.setMaximum(10000)
        self.popSize_SB.setProperty("value", 5)
        self.popSize_SB.setObjectName("popSize_SB")
        self.horizontalLayout_24.addWidget(self.popSize_SB)
        self.gridLayout_4.addLayout(self.horizontalLayout_24, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem18)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.copy_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.copy_SB.setMinimum(1)
        self.copy_SB.setObjectName("copy_SB")
        self.gridLayout_5.addWidget(self.copy_SB, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.mutate_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.mutate_SB.setMinimum(1)
        self.mutate_SB.setObjectName("mutate_SB")
        self.gridLayout_5.addWidget(self.mutate_SB, 1, 3, 1, 1)
        self.cross_SP = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.cross_SP.setMinimum(1)
        self.cross_SP.setObjectName("cross_SP")
        self.gridLayout_5.addWidget(self.cross_SP, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 2, 0, 1, 1)
        self.mutateRate_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.mutateRate_SB.setMinimum(10)
        self.mutateRate_SB.setMaximum(100)
        self.mutateRate_SB.setProperty("value", 50)
        self.mutateRate_SB.setObjectName("mutateRate_SB")
        self.gridLayout_5.addWidget(self.mutateRate_SB, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem19)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.estimatingWay_CB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.estimatingWay_CB.setObjectName("estimatingWay_CB")
        self.horizontalLayout_25.addWidget(self.estimatingWay_CB)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 281, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_32.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem20)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_32.addWidget(self.label_32)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBox.setMinimum(50)
        self.spinBox.setProperty("value", 70)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_32.addWidget(self.spinBox)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem21)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 5)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 5)
        self.verticalLayout_2.setStretch(5, 5)
        self.gridLayout_10.addWidget(self.groupBox, 1, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.gridLayoutWidget_10)
        self.groupBox_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_9.setAutoFillBackground(False)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_9)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 421, 161))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ReduceLR_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.ReduceLR_ChB.setObjectName("ReduceLR_ChB")
        self.gridLayout_6.addWidget(self.ReduceLR_ChB, 0, 3, 1, 1)
        self.tensorBoard_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.tensorBoard_ChB.setObjectName("tensorBoard_ChB")
        self.gridLayout_6.addWidget(self.tensorBoard_ChB, 1, 1, 1, 1)
        self.ProgbarLogger_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.ProgbarLogger_ChB.setObjectName("ProgbarLogger_ChB")
        self.gridLayout_6.addWidget(self.ProgbarLogger_ChB, 5, 3, 1, 1)
        self.earlyStopping_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.earlyStopping_ChB.setObjectName("earlyStopping_ChB")
        self.gridLayout_6.addWidget(self.earlyStopping_ChB, 2, 1, 1, 1)
        self.CSVLogger_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.CSVLogger_ChB.setObjectName("CSVLogger_ChB")
        self.gridLayout_6.addWidget(self.CSVLogger_ChB, 3, 3, 1, 1)
        self.lambda_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.lambda_ChB.setObjectName("lambda_ChB")
        self.gridLayout_6.addWidget(self.lambda_ChB, 2, 3, 1, 1)
        self.terminateNaN_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.terminateNaN_ChB.setObjectName("terminateNaN_ChB")
        self.gridLayout_6.addWidget(self.terminateNaN_ChB, 5, 1, 1, 1)
        self.remoteMonitor_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.remoteMonitor_ChB.setObjectName("remoteMonitor_ChB")
        self.gridLayout_6.addWidget(self.remoteMonitor_ChB, 1, 3, 1, 1)
        self.scheduler_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.scheduler_ChB.setObjectName("scheduler_ChB")
        self.gridLayout_6.addWidget(self.scheduler_ChB, 3, 1, 1, 1)
        self.modelCheckpoint_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.modelCheckpoint_ChB.setObjectName("modelCheckpoint_ChB")
        self.gridLayout_6.addWidget(self.modelCheckpoint_ChB, 0, 1, 1, 1)
        self.modelCheckpoint_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.modelCheckpoint_TB.setObjectName("modelCheckpoint_TB")
        self.gridLayout_6.addWidget(self.modelCheckpoint_TB, 0, 0, 1, 1)
        self.tensorBoard_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.tensorBoard_TB.setObjectName("tensorBoard_TB")
        self.gridLayout_6.addWidget(self.tensorBoard_TB, 1, 0, 1, 1)
        self.earlyStopping_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.earlyStopping_TB.setObjectName("earlyStopping_TB")
        self.gridLayout_6.addWidget(self.earlyStopping_TB, 2, 0, 1, 1)
        self.scheduler_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.scheduler_TB.setObjectName("scheduler_TB")
        self.gridLayout_6.addWidget(self.scheduler_TB, 3, 0, 1, 1)
        self.terminateNaN_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.terminateNaN_TB.setObjectName("terminateNaN_TB")
        self.gridLayout_6.addWidget(self.terminateNaN_TB, 5, 0, 1, 1)
        self.ReduceLR_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.ReduceLR_TB.setObjectName("ReduceLR_TB")
        self.gridLayout_6.addWidget(self.ReduceLR_TB, 0, 2, 1, 1)
        self.remoteMonitor_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.remoteMonitor_TB.setObjectName("remoteMonitor_TB")
        self.gridLayout_6.addWidget(self.remoteMonitor_TB, 1, 2, 1, 1)
        self.lambda_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.lambda_TB.setObjectName("lambda_TB")
        self.gridLayout_6.addWidget(self.lambda_TB, 2, 2, 1, 1)
        self.CSVLogger_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.CSVLogger_TB.setObjectName("CSVLogger_TB")
        self.gridLayout_6.addWidget(self.CSVLogger_TB, 3, 2, 1, 1)
        self.ProgbarLogger_TB = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.ProgbarLogger_TB.setObjectName("ProgbarLogger_TB")
        self.gridLayout_6.addWidget(self.ProgbarLogger_TB, 5, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_5 = QtWidgets.QGroupBox(self.gridLayoutWidget_10)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 421, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.search_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.search_Btn.setObjectName("search_Btn")
        self.horizontalLayout_27.addWidget(self.search_Btn)
        self.train_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.train_Btn.setObjectName("train_Btn")
        self.horizontalLayout_27.addWidget(self.train_Btn)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.groupBox_8 = QtWidgets.QGroupBox(self.gridLayoutWidget_10)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 421, 35))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.constLR_ChB = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.constLR_ChB.setChecked(True)
        self.constLR_ChB.setObjectName("constLR_ChB")
        self.horizontalLayout_30.addWidget(self.constLR_ChB)
        self.minLR_dSB = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.minLR_dSB.setDecimals(3)
        self.minLR_dSB.setMinimum(0.001)
        self.minLR_dSB.setObjectName("minLR_dSB")
        self.horizontalLayout_30.addWidget(self.minLR_dSB)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_30.addWidget(self.label_30)
        self.maxLR_dSB = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.maxLR_dSB.setDecimals(3)
        self.maxLR_dSB.setObjectName("maxLR_dSB")
        self.horizontalLayout_30.addWidget(self.maxLR_dSB)
        self.horizontalLayout_30.setStretch(1, 1)
        self.horizontalLayout_30.setStretch(3, 1)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.adaptiveLR_ChB = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.adaptiveLR_ChB.setObjectName("adaptiveLR_ChB")
        self.horizontalLayout_4.addWidget(self.adaptiveLR_ChB)
        self.spinBox_17 = QtWidgets.QSpinBox(self.horizontalLayoutWidget_5)
        self.spinBox_17.setObjectName("spinBox_17")
        self.horizontalLayout_4.addWidget(self.spinBox_17)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.setStretch(0, 181)
        self.verticalLayout_5.setStretch(1, 81)
        self.verticalLayout_5.setStretch(2, 85)
        self.gridLayout_10.addLayout(self.verticalLayout_5, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_10.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.gridLayoutWidget_10)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 351, 251))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem22)
        self.min_filersPowIndex_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.min_filersPowIndex_SB.setMinimum(3)
        self.min_filersPowIndex_SB.setObjectName("min_filersPowIndex_SB")
        self.horizontalLayout_18.addWidget(self.min_filersPowIndex_SB)
        self.max_filersPowIndex_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.max_filersPowIndex_SB.setMinimum(3)
        self.max_filersPowIndex_SB.setProperty("value", 5)
        self.max_filersPowIndex_SB.setObjectName("max_filersPowIndex_SB")
        self.horizontalLayout_18.addWidget(self.max_filersPowIndex_SB)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem23)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.maxDense_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.maxDense_SB.setMinimum(1)
        self.maxDense_SB.setProperty("value", 5)
        self.maxDense_SB.setObjectName("maxDense_SB")
        self.horizontalLayout_19.addWidget(self.maxDense_SB)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem25)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem26)
        self.cDropout_ChB = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.cDropout_ChB.setText("")
        self.cDropout_ChB.setObjectName("cDropout_ChB")
        self.horizontalLayout_2.addWidget(self.cDropout_ChB)
        self.cMaxDropout_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.cMaxDropout_SB.setMinimum(10)
        self.cMaxDropout_SB.setMaximum(99)
        self.cMaxDropout_SB.setProperty("value", 30)
        self.cMaxDropout_SB.setObjectName("cMaxDropout_SB")
        self.horizontalLayout_2.addWidget(self.cMaxDropout_SB)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem27)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(3, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem28)
        self.min_neuronsPowIndex_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.min_neuronsPowIndex_SB.setMinimum(3)
        self.min_neuronsPowIndex_SB.setObjectName("min_neuronsPowIndex_SB")
        self.horizontalLayout_20.addWidget(self.min_neuronsPowIndex_SB)
        self.max_neuronsPowIndex_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.max_neuronsPowIndex_SB.setMinimum(3)
        self.max_neuronsPowIndex_SB.setProperty("value", 5)
        self.max_neuronsPowIndex_SB.setObjectName("max_neuronsPowIndex_SB")
        self.horizontalLayout_20.addWidget(self.max_neuronsPowIndex_SB)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem29)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem30)
        self.dDropout_ChB = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.dDropout_ChB.setText("")
        self.dDropout_ChB.setObjectName("dDropout_ChB")
        self.horizontalLayout_3.addWidget(self.dDropout_ChB)
        self.dMaxDropout_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.dMaxDropout_SB.setMinimum(10)
        self.dMaxDropout_SB.setProperty("value", 30)
        self.dMaxDropout_SB.setObjectName("dMaxDropout_SB")
        self.horizontalLayout_3.addWidget(self.dMaxDropout_SB)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem31)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(3, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem32)
        self.maxConv_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.maxConv_SB.setMinimum(1)
        self.maxConv_SB.setProperty("value", 5)
        self.maxConv_SB.setObjectName("maxConv_SB")
        self.horizontalLayout_17.addWidget(self.maxConv_SB)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem33)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem34)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem35)
        self.xKernel_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.xKernel_SB.setMinimum(2)
        self.xKernel_SB.setProperty("value", 7)
        self.xKernel_SB.setObjectName("xKernel_SB")
        self.horizontalLayout_21.addWidget(self.xKernel_SB)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem36)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem37)
        self.yKernel_SB = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.yKernel_SB.setMinimum(2)
        self.yKernel_SB.setProperty("value", 7)
        self.yKernel_SB.setObjectName("yKernel_SB")
        self.horizontalLayout_22.addWidget(self.yKernel_SB)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem38)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_28.addLayout(self.verticalLayout)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem39)
        self.horizontalLayout_28.setStretch(0, 1)
        self.horizontalLayout_28.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.verticalLayout_3.setStretch(2, 1)
        self.gridLayout_10.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 367)
        self.gridLayout_10.setColumnStretch(1, 292)
        self.gridLayout_10.setColumnStretch(2, 431)
        self.gridLayout_10.setRowStretch(0, 1)
        self.gridLayout_10.setRowStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1630, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen_program = QtWidgets.QMenu(self.menuFile)
        self.menuOpen_program.setObjectName("menuOpen_program")
        self.menuWindows = QtWidgets.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionPipeline_Editor = QtWidgets.QAction(MainWindow)
        self.actionPipeline_Editor.setObjectName("actionPipeline_Editor")
        self.actionModel_Editor = QtWidgets.QAction(MainWindow)
        self.actionModel_Editor.setObjectName("actionModel_Editor")
        self.actionProperties = QtWidgets.QAction(MainWindow)
        self.actionProperties.setObjectName("actionProperties")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOpen_program.addAction(self.actionOpen)
        self.menuOpen_program.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuOpen_program.menuAction())
        self.menuWindows.addAction(self.actionPipeline_Editor)
        self.menuWindows.addAction(self.actionModel_Editor)
        self.menuWindows.addSeparator()
        self.menuWindows.addAction(self.actionProperties)
        self.menuWindows.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convolutional 2D"))
        self.optAdam_ChB.setText(_translate("MainWindow", "Adam"))
        self.optSGD_ChB.setText(_translate("MainWindow", "SGD"))
        self.optAdadelta_ChB.setText(_translate("MainWindow", "Adadelta"))
        self.optAdagrad_ChB.setText(_translate("MainWindow", "Adagrad"))
        self.optAdamax_ChB.setText(_translate("MainWindow", "Adamax"))
        self.optRMSprop_ChB.setText(_translate("MainWindow", "RMSprop"))
        self.optNadam_ChB.setText(_translate("MainWindow", "Nadam"))
        self.label.setText(_translate("MainWindow", "Activation Function"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Optimizer</p></body></html>"))
        self.dSoftMax_ChB.setText(_translate("MainWindow", "SoftMax"))
        self.dSELU_ChB.setText(_translate("MainWindow", "SELU"))
        self.dReLU_ChB.setText(_translate("MainWindow", "ReLU"))
        self.dSigmoid_ChB.setText(_translate("MainWindow", "Sigmoid"))
        self.dTReLU_ChB.setText(_translate("MainWindow", "TReLU"))
        self.dELU_ChB.setText(_translate("MainWindow", "ELU"))
        self.dSoftSign_ChB.setText(_translate("MainWindow", "SoftSign"))
        self.dTanh_ChB.setText(_translate("MainWindow", "Tanh"))
        self.dLReLU_ChB.setText(_translate("MainWindow", "LReLU"))
        self.dSoftPlus_ChB.setText(_translate("MainWindow", "SoftPlus"))
        self.dPReLU_ChB.setText(_translate("MainWindow", "PReLU"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>Loss function</p></body></html>"))
        self.lf_MSE_ChB.setText(_translate("MainWindow", "MSE"))
        self.lf_MAPE_ChB.setText(_translate("MainWindow", "MAPE"))
        self.lf_sqHingle_ChB.setText(_translate("MainWindow", "Squared hinge"))
        self.lf_Poisson_ChB.setText(_translate("MainWindow", "Poisson"))
        self.lf_Logcosh.setText(_translate("MainWindow", "Logcosh"))
        self.lf_CCE_ChB.setText(_translate("MainWindow", "Categorical crossentropy"))
        self.lf_sCCE_ChB.setText(_translate("MainWindow", "SCategorical crossentropy"))
        self.lf_Hingle_ChB.setText(_translate("MainWindow", "Hinge"))
        self.lf_cHingle_ChB.setText(_translate("MainWindow", "Categorical hinge"))
        self.lf_KDL_ChB.setText(_translate("MainWindow", "KLD"))
        self.lf_BCE_ChB.setText(_translate("MainWindow", "Binary crossentropy"))
        self.lf_MAE_ChB.setText(_translate("MainWindow", "MAE"))
        self.lf_MSLE_ChB.setText(_translate("MainWindow", "MSLE"))
        self.lf_CosProx_ChB.setText(_translate("MainWindow", "Cosine proximity"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Batch Size</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Epoch"))
        self.label_5.setText(_translate("MainWindow", "Labels"))
        self.DatasetPath_LE.setText(_translate("MainWindow", "D:\\keras\\datasets\\animals"))
        self.ModelPath_LE.setText(_translate("MainWindow", "C:\\keras\\Directory\\models"))
        self.Labels_LE.setText(_translate("MainWindow", "C:\\keras\\Directory\\labels"))
        self.label_3.setText(_translate("MainWindow", "Plots"))
        self.PlotsPath_LE.setText(_translate("MainWindow", "C:\\keras\\Directory\\plots"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Models</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Dataset"))
        self.DatasetPath_TB.setText(_translate("MainWindow", "..."))
        self.ModelsPath_TB.setText(_translate("MainWindow", "..."))
        self.LabelPath_TB.setText(_translate("MainWindow", "..."))
        self.PlotPath_TB.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Additionals"))
        self.label_15.setText(_translate("MainWindow", "Network Name"))
        self.label_18.setText(_translate("MainWindow", "Epoch of evolution"))
        self.label_17.setText(_translate("MainWindow", "Population Size"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Cross</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mutate</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Copy</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Proportions</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Mutate Rate</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "%"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>Estimating</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "Threshold value"))
        self.ReduceLR_ChB.setText(_translate("MainWindow", "Reduce LR On Plateau"))
        self.tensorBoard_ChB.setText(_translate("MainWindow", "Tensor Board"))
        self.ProgbarLogger_ChB.setText(_translate("MainWindow", "Progbar Logger"))
        self.earlyStopping_ChB.setText(_translate("MainWindow", "Early Stopping"))
        self.CSVLogger_ChB.setText(_translate("MainWindow", "CSV Logger"))
        self.lambda_ChB.setText(_translate("MainWindow", "Lambda Callback"))
        self.terminateNaN_ChB.setText(_translate("MainWindow", "Terminate On NaN"))
        self.remoteMonitor_ChB.setText(_translate("MainWindow", "Remote Monitor"))
        self.scheduler_ChB.setText(_translate("MainWindow", "Learning Rate Scheduler"))
        self.modelCheckpoint_ChB.setText(_translate("MainWindow", "Model Checkpoint"))
        self.modelCheckpoint_TB.setText(_translate("MainWindow", "..."))
        self.tensorBoard_TB.setText(_translate("MainWindow", "..."))
        self.earlyStopping_TB.setText(_translate("MainWindow", "..."))
        self.scheduler_TB.setText(_translate("MainWindow", "..."))
        self.terminateNaN_TB.setText(_translate("MainWindow", "..."))
        self.ReduceLR_TB.setText(_translate("MainWindow", "..."))
        self.remoteMonitor_TB.setText(_translate("MainWindow", "..."))
        self.lambda_TB.setText(_translate("MainWindow", "..."))
        self.CSVLogger_TB.setText(_translate("MainWindow", "..."))
        self.ProgbarLogger_TB.setText(_translate("MainWindow", "..."))
        self.search_Btn.setText(_translate("MainWindow", "Add to Queue"))
        self.train_Btn.setText(_translate("MainWindow", "Show Queue"))
        self.label_29.setText(_translate("MainWindow", "Learning Rate Rule"))
        self.constLR_ChB.setText(_translate("MainWindow", "Const"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">-</p></body></html>"))
        self.adaptiveLR_ChB.setText(_translate("MainWindow", "Adaptive"))
        self.label_31.setText(_translate("MainWindow", "Callbacks"))
        self.label_26.setText(_translate("MainWindow", "Genetic properties"))
        self.label_16.setText(_translate("MainWindow", "Structure"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Max layers</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Dropout</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Filters or Neurons<br/>pow index </p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Convolutional"))
        self.label_10.setText(_translate("MainWindow", "Dense"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Kernel</p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen_program.setTitle(_translate("MainWindow", "Open program"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionPipeline_Editor.setText(_translate("MainWindow", "Pipeline Editor"))
        self.actionModel_Editor.setText(_translate("MainWindow", "Model Editor"))
        self.actionProperties.setText(_translate("MainWindow", "Properties"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
