# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/Parents/Designer_gui/ModelCheckpoint_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelCheckpointWindow(object):
    def setupUi(self, ModelCheckpointWindow):
        ModelCheckpointWindow.setObjectName("ModelCheckpointWindow")
        ModelCheckpointWindow.resize(536, 281)
        self.frame = QtWidgets.QFrame(ModelCheckpointWindow)
        self.frame.setGeometry(QtCore.QRect(10, 10, 521, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 501, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.path_LE = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.path_LE.setObjectName("path_LE")
        self.horizontalLayout.addWidget(self.path_LE)
        self.toolButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 501, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.monitor_CB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.monitor_CB.setObjectName("monitor_CB")
        self.gridLayout.addWidget(self.monitor_CB, 0, 1, 1, 1)
        self.mode_CB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.mode_CB.setObjectName("mode_CB")
        self.gridLayout.addWidget(self.mode_CB, 1, 1, 1, 1)
        self.save_freq_CB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.save_freq_CB.setObjectName("save_freq_CB")
        self.gridLayout.addWidget(self.save_freq_CB, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.weights_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.weights_ChB.setObjectName("weights_ChB")
        self.gridLayout.addWidget(self.weights_ChB, 0, 2, 1, 1)
        self.verbose_ChB = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.verbose_ChB.setObjectName("verbose_ChB")
        self.gridLayout.addWidget(self.verbose_ChB, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 190, 501, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.default_ChB = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.default_ChB.setObjectName("default_ChB")
        self.horizontalLayout_2.addWidget(self.default_ChB)
        self.OK_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.OK_Btn.setObjectName("OK_Btn")
        self.horizontalLayout_2.addWidget(self.OK_Btn)
        self.cancel_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.cancel_Btn.setObjectName("cancel_Btn")
        self.horizontalLayout_2.addWidget(self.cancel_Btn)

        self.retranslateUi(ModelCheckpointWindow)
        QtCore.QMetaObject.connectSlotsByName(ModelCheckpointWindow)

    def retranslateUi(self, ModelCheckpointWindow):
        _translate = QtCore.QCoreApplication.translate
        ModelCheckpointWindow.setWindowTitle(_translate("ModelCheckpointWindow", "Model Checkpoint Callback Properties"))
        self.label.setText(_translate("ModelCheckpointWindow", "File Path"))
        self.toolButton.setText(_translate("ModelCheckpointWindow", "..."))
        self.label_3.setText(_translate("ModelCheckpointWindow", "Mode"))
        self.checkBox_3.setText(_translate("ModelCheckpointWindow", "Save weights only"))
        self.label_4.setText(_translate("ModelCheckpointWindow", "Save freq"))
        self.label_2.setText(_translate("ModelCheckpointWindow", "Monitor"))
        self.weights_ChB.setText(_translate("ModelCheckpointWindow", "Save best only"))
        self.verbose_ChB.setText(_translate("ModelCheckpointWindow", "verbose"))
        self.default_ChB.setText(_translate("ModelCheckpointWindow", "set as Default params"))
        self.OK_Btn.setText(_translate("ModelCheckpointWindow", "OK"))
        self.cancel_Btn.setText(_translate("ModelCheckpointWindow", "Cancel"))
