# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/Parents/Designer_gui/StartPage_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartPageWindow(object):
    def setupUi(self, StartPageWindow):
        StartPageWindow.setObjectName("StartPageWindow")
        StartPageWindow.resize(1688, 857)
        self.centralwidget = QtWidgets.QWidget(StartPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 650, 231, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.modes_TW = QtWidgets.QTabWidget(self.centralwidget)
        self.modes_TW.setGeometry(QtCore.QRect(20, 10, 471, 621))
        self.modes_TW.setObjectName("modes_TW")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.active_projects_LW = QtWidgets.QListWidget(self.tab_7)
        self.active_projects_LW.setGeometry(QtCore.QRect(10, 10, 441, 571))
        self.active_projects_LW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.active_projects_LW.setObjectName("active_projects_LW")
        self.modes_TW.addTab(self.tab_7, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.archive_projects_LW = QtWidgets.QListWidget(self.tab_10)
        self.archive_projects_LW.setGeometry(QtCore.QRect(10, 10, 451, 571))
        self.archive_projects_LW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.archive_projects_LW.setObjectName("archive_projects_LW")
        self.modes_TW.addTab(self.tab_10, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.queue_projects_LW = QtWidgets.QListWidget(self.tab_8)
        self.queue_projects_LW.setGeometry(QtCore.QRect(10, 10, 451, 571))
        self.queue_projects_LW.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.queue_projects_LW.setObjectName("queue_projects_LW")
        self.modes_TW.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 451, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 421, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 391, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.opt_method_CB = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.opt_method_CB.setObjectName("opt_method_CB")
        self.gridLayout_2.addWidget(self.opt_method_CB, 1, 1, 1, 1)
        self.opt_project_type_CB = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.opt_project_type_CB.setObjectName("opt_project_type_CB")
        self.gridLayout_2.addWidget(self.opt_project_type_CB, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.opt_project_name_LE = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.opt_project_name_LE.setObjectName("opt_project_name_LE")
        self.gridLayout_2.addWidget(self.opt_project_name_LE, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.opt_project_path_LE = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.opt_project_path_LE.setObjectName("opt_project_path_LE")
        self.gridLayout_2.addWidget(self.opt_project_path_LE, 3, 1, 1, 1)
        self.opt_path_TB = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.opt_path_TB.setObjectName("opt_path_TB")
        self.gridLayout_2.addWidget(self.opt_path_TB, 3, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 200, 421, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.opt_open_Btn = QtWidgets.QPushButton(self.layoutWidget)
        self.opt_open_Btn.setObjectName("opt_open_Btn")
        self.horizontalLayout_4.addWidget(self.opt_open_Btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.opt_create_Btn = QtWidgets.QPushButton(self.layoutWidget)
        self.opt_create_Btn.setObjectName("opt_create_Btn")
        self.horizontalLayout_4.addWidget(self.opt_create_Btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame1 = QtWidgets.QFrame(self.tab_2)
        self.frame1.setGeometry(QtCore.QRect(10, 10, 421, 181))
        self.frame1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame1.setObjectName("frame1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 391, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.dataset_path_TB = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.dataset_path_TB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataset_path_TB.setAutoFillBackground(False)
        self.dataset_path_TB.setObjectName("dataset_path_TB")
        self.gridLayout.addWidget(self.dataset_path_TB, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.saveTo_TB = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.saveTo_TB.setObjectName("saveTo_TB")
        self.gridLayout.addWidget(self.saveTo_TB, 3, 2, 1, 1)
        self.saveTo_path_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.saveTo_path_LE.setObjectName("saveTo_path_LE")
        self.gridLayout.addWidget(self.saveTo_path_LE, 3, 1, 1, 1)
        self.app_model_CB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.app_model_CB.setObjectName("app_model_CB")
        self.gridLayout.addWidget(self.app_model_CB, 0, 1, 1, 1)
        self.app_dataset_path_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.app_dataset_path_LE.setObjectName("app_dataset_path_LE")
        self.gridLayout.addWidget(self.app_dataset_path_LE, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.app_project_name_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.app_project_name_LE.setObjectName("app_project_name_LE")
        self.gridLayout.addWidget(self.app_project_name_LE, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 200, 421, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 401, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.app_open_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.app_open_Btn.setObjectName("app_open_Btn")
        self.horizontalLayout_7.addWidget(self.app_open_Btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.app_create_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.app_create_Btn.setObjectName("app_create_Btn")
        self.horizontalLayout_7.addWidget(self.app_create_Btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.modes_TW.addTab(self.tab_9, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_4 = QtWidgets.QFrame(self.tab_5)
        self.frame_4.setGeometry(QtCore.QRect(20, 40, 421, 181))
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 401, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.predict_problem_CB = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.predict_problem_CB.setObjectName("predict_problem_CB")
        self.gridLayout_4.addWidget(self.predict_problem_CB, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.predict_datatype_CB = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.predict_datatype_CB.setObjectName("predict_datatype_CB")
        self.gridLayout_4.addWidget(self.predict_datatype_CB, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.predict_letsgo_Btn = QtWidgets.QPushButton(self.tab_5)
        self.predict_letsgo_Btn.setGeometry(QtCore.QRect(120, 240, 201, 28))
        self.predict_letsgo_Btn.setObjectName("predict_letsgo_Btn")
        self.modes_TW.addTab(self.tab_5, "")
        self.output_TW = QtWidgets.QTabWidget(self.centralwidget)
        self.output_TW.setGeometry(QtCore.QRect(500, 10, 541, 621))
        self.output_TW.setObjectName("output_TW")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.output_1_TE = QtWidgets.QTextEdit(self.tab_3)
        self.output_1_TE.setGeometry(QtCore.QRect(10, 10, 511, 571))
        self.output_1_TE.setObjectName("output_1_TE")
        self.output_TW.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.output_2_TE_2 = QtWidgets.QTextEdit(self.tab_6)
        self.output_2_TE_2.setGeometry(QtCore.QRect(10, 10, 511, 571))
        self.output_2_TE_2.setObjectName("output_2_TE_2")
        self.output_TW.addTab(self.tab_6, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.erroneous_output_TE = QtWidgets.QTextEdit(self.tab_11)
        self.erroneous_output_TE.setGeometry(QtCore.QRect(10, 10, 511, 571))
        self.erroneous_output_TE.setObjectName("erroneous_output_TE")
        self.output_TW.addTab(self.tab_11, "")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(1060, 30, 591, 601))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.plot_W = QtWidgets.QWidget(self.frame_5)
        self.plot_W.setGeometry(QtCore.QRect(10, 10, 561, 571))
        self.plot_W.setObjectName("plot_W")
        StartPageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartPageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1688, 25))
        self.menubar.setObjectName("menubar")
        StartPageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartPageWindow)
        self.statusbar.setObjectName("statusbar")
        StartPageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartPageWindow)
        self.modes_TW.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.output_TW.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StartPageWindow)

    def retranslateUi(self, StartPageWindow):
        _translate = QtCore.QCoreApplication.translate
        StartPageWindow.setWindowTitle(_translate("StartPageWindow", "NN Family Creater - Start Page"))
        self.pushButton_3.setText(_translate("StartPageWindow", "Task Manager"))
        self.modes_TW.setTabText(self.modes_TW.indexOf(self.tab_7), _translate("StartPageWindow", "Tab 1"))
        self.modes_TW.setTabText(self.modes_TW.indexOf(self.tab_10), _translate("StartPageWindow", "Page"))
        self.modes_TW.setTabText(self.modes_TW.indexOf(self.tab_8), _translate("StartPageWindow", "Tab 2"))
        self.label_4.setText(_translate("StartPageWindow", "Project name"))
        self.label_6.setText(_translate("StartPageWindow", "Use"))
        self.label_2.setText(_translate("StartPageWindow", "Create"))
        self.label_3.setText(_translate("StartPageWindow", "model"))
        self.label_7.setText(_translate("StartPageWindow", "mode"))
        self.label_5.setText(_translate("StartPageWindow", "Project path"))
        self.opt_path_TB.setText(_translate("StartPageWindow", "..."))
        self.opt_open_Btn.setText(_translate("StartPageWindow", "Open"))
        self.opt_create_Btn.setText(_translate("StartPageWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("StartPageWindow", "Tab 1"))
        self.label_9.setText(_translate("StartPageWindow", "model"))
        self.label_11.setText(_translate("StartPageWindow", "Save to"))
        self.dataset_path_TB.setText(_translate("StartPageWindow", "..."))
        self.label_8.setText(_translate("StartPageWindow", "Create"))
        self.label_10.setText(_translate("StartPageWindow", "Dataset path"))
        self.saveTo_TB.setText(_translate("StartPageWindow", "..."))
        self.label_15.setText(_translate("StartPageWindow", "Project name"))
        self.app_open_Btn.setText(_translate("StartPageWindow", "Open"))
        self.app_create_Btn.setText(_translate("StartPageWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("StartPageWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("StartPageWindow", "Page"))
        self.modes_TW.setTabText(self.modes_TW.indexOf(self.tab_9), _translate("StartPageWindow", "Page"))
        self.label_12.setText(_translate("StartPageWindow", "Predict"))
        self.label_13.setText(_translate("StartPageWindow", "problem"))
        self.label_14.setText(_translate("StartPageWindow", "Type of input data"))
        self.predict_letsgo_Btn.setText(_translate("StartPageWindow", "Lets go"))
        self.modes_TW.setTabText(self.modes_TW.indexOf(self.tab_5), _translate("StartPageWindow", "Page"))
        self.output_TW.setTabText(self.output_TW.indexOf(self.tab_3), _translate("StartPageWindow", "Tab 1"))
        self.output_TW.setTabText(self.output_TW.indexOf(self.tab_6), _translate("StartPageWindow", "Tab 2"))
        self.output_TW.setTabText(self.output_TW.indexOf(self.tab_11), _translate("StartPageWindow", "Page"))
