# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms\Parents\Designer_gui\StartPage_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartPageWindow(object):
    def setupUi(self, StartPageWindow):
        StartPageWindow.setObjectName("StartPageWindow")
        StartPageWindow.resize(847, 603)
        self.centralwidget = QtWidgets.QWidget(StartPageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 131, 21))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 40, 231, 451))
        self.textEdit.setObjectName("textEdit")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(210, 40, 21, 451))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(240, 220, 571, 301))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 541, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 521, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 3, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(80, 200, 391, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame1 = QtWidgets.QFrame(self.tab_2)
        self.frame1.setGeometry(QtCore.QRect(10, 10, 541, 181))
        self.frame1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame1.setObjectName("frame1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.dataset_path_TB = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.dataset_path_TB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataset_path_TB.setAutoFillBackground(False)
        self.dataset_path_TB.setObjectName("dataset_path_TB")
        self.gridLayout.addWidget(self.dataset_path_TB, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.saveTo_TB = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.saveTo_TB.setObjectName("saveTo_TB")
        self.gridLayout.addWidget(self.saveTo_TB, 3, 2, 1, 1)
        self.saveTo_path_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.saveTo_path_LE.setObjectName("saveTo_path_LE")
        self.gridLayout.addWidget(self.saveTo_path_LE, 3, 1, 1, 1)
        self.app_model_CB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.app_model_CB.setObjectName("app_model_CB")
        self.gridLayout.addWidget(self.app_model_CB, 0, 1, 1, 1)
        self.app_dataset_path_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.app_dataset_path_LE.setObjectName("app_dataset_path_LE")
        self.gridLayout.addWidget(self.app_dataset_path_LE, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.app_project_name_LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.app_project_name_LE.setObjectName("app_project_name_LE")
        self.gridLayout.addWidget(self.app_project_name_LE, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(80, 200, 391, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 371, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.app_open_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.app_open_Btn.setObjectName("app_open_Btn")
        self.horizontalLayout_7.addWidget(self.app_open_Btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.app_create_Btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.app_create_Btn.setObjectName("app_create_Btn")
        self.horizontalLayout_7.addWidget(self.app_create_Btn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 541, 181))
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 511, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.predict_problem_CB = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.predict_problem_CB.setObjectName("predict_problem_CB")
        self.gridLayout_3.addWidget(self.predict_problem_CB, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.predict_datatype_CB = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.predict_datatype_CB.setObjectName("predict_datatype_CB")
        self.gridLayout_3.addWidget(self.predict_datatype_CB, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 4, 1, 1)
        self.predict_letsgo_Btn = QtWidgets.QPushButton(self.tab_3)
        self.predict_letsgo_Btn.setGeometry(QtCore.QRect(170, 210, 201, 28))
        self.predict_letsgo_Btn.setObjectName("predict_letsgo_Btn")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 490, 231, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        StartPageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartPageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 25))
        self.menubar.setObjectName("menubar")
        StartPageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartPageWindow)
        self.statusbar.setObjectName("statusbar")
        StartPageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartPageWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(StartPageWindow)

    def retranslateUi(self, StartPageWindow):
        _translate = QtCore.QCoreApplication.translate
        StartPageWindow.setWindowTitle(_translate("StartPageWindow", "NN Family Creater - Start Page"))
        self.label.setText(_translate("StartPageWindow", "Opent recent project"))
        self.label_4.setText(_translate("StartPageWindow", "Project name"))
        self.label_6.setText(_translate("StartPageWindow", "Use"))
        self.label_2.setText(_translate("StartPageWindow", "Create"))
        self.label_3.setText(_translate("StartPageWindow", "model"))
        self.label_7.setText(_translate("StartPageWindow", "mode"))
        self.label_5.setText(_translate("StartPageWindow", "Project path"))
        self.toolButton.setText(_translate("StartPageWindow", "..."))
        self.pushButton.setText(_translate("StartPageWindow", "Open"))
        self.pushButton_2.setText(_translate("StartPageWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("StartPageWindow", "Tab 1"))
        self.label_9.setText(_translate("StartPageWindow", "model"))
        self.label_11.setText(_translate("StartPageWindow", "Save to"))
        self.dataset_path_TB.setText(_translate("StartPageWindow", "..."))
        self.label_8.setText(_translate("StartPageWindow", "Create"))
        self.label_10.setText(_translate("StartPageWindow", "Dataset path"))
        self.saveTo_TB.setText(_translate("StartPageWindow", "..."))
        self.label_15.setText(_translate("StartPageWindow", "Project name"))
        self.app_open_Btn.setText(_translate("StartPageWindow", "Open"))
        self.app_create_Btn.setText(_translate("StartPageWindow", "Create"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("StartPageWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("StartPageWindow", "Page"))
        self.label_14.setText(_translate("StartPageWindow", "Type of input data"))
        self.label_12.setText(_translate("StartPageWindow", "Predict"))
        self.label_13.setText(_translate("StartPageWindow", "problem"))
        self.predict_letsgo_Btn.setText(_translate("StartPageWindow", "Lets go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("StartPageWindow", "Page"))
        self.pushButton_3.setText(_translate("StartPageWindow", "Task Manager"))
